### ISSUE TITLE
升级新版本后一直报错

### ISSUE THREAD

**Issue by a158684** [sionsxie/arms-template-plugin#23]
Task :runIde FAILED
[gradle-intellij-plugin :arms-template-plugin:runIde] Cannot find java executable in: C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.jetbrains\jbre\jbr-17.0.5-windows-x64-b653.23\extracted
[gradle-intellij-plugin :arms-template-plugin:runIde] Cannot resolve runtime with ideDir='C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2022.3.1\2a2986db4e11c3d378b4d1c8b9fd040cd6d99802\ideaIC-2022.3.1', version='version'
[gradle-intellij-plugin :arms-template-plugin:runIde] Cannot resolve runtime with ideDir='C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.jetbrains.intellij.idea\ideaIC\2022.3.1\2a2986db4e11c3d378b4d1c8b9fd040cd6d99802\ideaIC-2022.3.1'
����: �Ҳ������޷��������� com.intellij.idea.Main
ԭ��: java.lang.ClassNotFoundException: com.intellij.idea.Main

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runIde'.
> Process 'command 'G:\Program Files\Android\Android Studio\jbr\bin\java.exe'' finished with non-zero exit value 1
![image](https://github.com/sionsxie/arms-template-plugin/assets/15867955/516031ba-3a89-42a0-97b4-4c5c3e084e82)
![image](https://github.com/sionsxie/arms-template-plugin/assets/15867955/bb17434f-f3a5-4d68-ba41-12f82c372b09)
麻烦大佬帮忙看看

**Comment by sionsxie** [comment]
版本问题，从 https://github.com/JetBrains/intellij-platform-plugin-template 拉最新模板的 改改就好了
