### ISSUE TITLE
Clone了代码，Syna Project With Gradle Files的时候一直报错，求帮助

### ISSUE THREAD

**Issue by dwtedx** [sionsxie/arms-template-plugin#4]
Clone了代码，Syna Project With Gradle Files的时候一直报错 “Unable to load class 'com.android.ide.gradle.model.impl.GradlePluginModelImpl'.”，求大佬帮忙解决一下

**Comment by cyl1996219** [comment]
Failed to calculate the value of property 'namespace'.
org.xml.sax.SAXParseException; systemId: file:/E:/NewCode/MyApplication/app/src/main/AndroidManifest.xml; lineNumber: 16; columnNumber: 12; 尾随节中不允许有内容。
尾随节中不允许有内容。
